### ISSUE TITLE
tab complete username

### ISSUE THREAD

**Issue by mafintosh** [moose-team/friends#11]
`mafi<tab>` should expand to `mafintosh: ` like irc cloud. if more than one user has the same prefix it could just cycle through them on subsequent `<tab>`s

**Comment by beaugunderson** [comment]
we talked about @-mentions for users not currently in chat too, maybe the list comes from who you're following on github but is prioritized by who's currently connected in chat?

**Comment by ngoldman** [comment]
irc clients like irc cloud tend to autocomplete only from people that are present.. also i have reservations about binding things really tightly with github. with that said it would be a neat feature and could be rejiggered to be more third-party-vendor-agnostic in the future

**Comment by shama** [comment]
We could add a property to the `composer` element with an array of autocomplete words. Then when typing it searches/autocompletes from those. Keeps it generic and up to the app which words autocomplete.

**Comment by ngoldman** [comment]
sounds modular! :sparkles:

**Comment by shama** [comment]
The above implements tab autocomplete for user names. But only the first found word.

Still need to cycle through additionally found words on tab.

**Comment by meandavejustice** [comment]
Couple things I noticed.
* Should also disable tabbing out of composer when focused on input.
* Should be able to tab complete more than one username

**Comment by Flet** [comment]
Some autocomplete changes from last night: #32 https://github.com/moose-team/friends/commit/9b32f2b37f0276bc1ebf9db26ff0868c2037767e

Prevent tabbing away from composer if it has text in it (still keeps _some_ accessibility):
https://github.com/moose-team/friends/commit/dc6c107df90aa277bfd461d3812b2b52f549613e

@shama I apologize if this conflicts with your word-cycling intentions!

**Comment by shama** [comment]
@Flet Nope! Thanks for your rad fixes :D
