### ISSUE TITLE
Externalize "/" commands

### ISSUE THREAD

**Issue by pokemonmegaman** [moose-team/friends#117]
It would be excellent if instead of having a big switch in the middle of app.js we could have a `commands.js` file that contains all the commands in their own objects.  Command objects should have the function they will run, a description of what they do (to be later used  in `/help`, and preferably a list of built-in aliases for each command.

**Comment by bcomnes** [comment]
It doesn't cover everything here, but we can at least get all of this out of app.js

**Comment by pokemonmegaman** [comment]
It seems good enough for now.  I'll make `/help` a separate issue.
