### ISSUE TITLE
readability wishlist

### ISSUE THREAD

**Issue by beaugunderson** [moose-team/friends#12]
- [x] style your own messages differently (so it's easy to see "what's been said since I last sent a message")
- [x] multiple sequential messages within a short time (2 minutes?) from the same person are collapsed (don't repeat name/avatar for each message)

**Comment by ngoldman** [comment]
agreement

**Comment by feross** [comment]
Both of these items are done now :-)

**Comment by feross** [comment]
https://github.com/moose-team/friends/commit/979ba73e74ec33fb1a9f5c46ba0fa3a1e0eb7233

**Comment by feross** [comment]
Actually, decided against coloring usernames after all. Looks weird. Not really necessary since we have avatars.

**Comment by beaugunderson** [comment]
was thinking maybe slightly shaded background would make it apparent?

---
