### ISSUE TITLE
Retain message scroll state

### ISSUE THREAD

**Issue by shama** [moose-team/friends#13]
Currently it will scroll to the bottom of the messages when a new message is received making it difficult to scroll back when people are talking.

It should scroll to the bottom automatically unless the user has scrolled up.

**Comment by maxogden** [comment]
along with this we should track every message that has been viewed/not yet viewed. e.g. by default all are unviewed. if it is displayed on the screen it will get marked as viewed. 

then we can do stuff like this UI in chrome when you CMD+F for a string:

![screen shot 2015-04-27 at 12 38 34 pm](https://cloud.githubusercontent.com/assets/39759/7355982/5ca6d63c-ecda-11e4-9eb1-def8e93304a3.png)

except in our use case yellow will mean 'theres an unread message(s) here'

**Comment by ngoldman** [comment]
:+1:
