### ISSUE TITLE
signalhubs are not working

### ISSUE THREAD

**Issue by Flet** [moose-team/friends#135]
Not sure what exactly the issue is, but I'm having no luck getting any peers. I suspect there may be problems with all of the default signalhubs:
```
      'https://signalhub.publicbits.org',
      'https://signalhub.mafintosh.com',
      'https://beaugunderson.com/signalhub',
      'http://dev.mathiasbuus.eu:8080' // deprecated
```

I tested each one separately as a single hub and still had no luck connecting two peers.

However, I spun up a little hub of my own (`http://flet.io:8081`) and was able to successfully connect two peers.

Can anyone else confim that one or many of the signalhubs are not working?

@mafintosh @maxogden @beaugunderson

**Comment by beaugunderson** [comment]
does friends connect to all of them or are they round-robined?

i just upgraded mine to 4.1.0, let's see if that does anything (max' is 3.4.0 and mathias' is 4.0.2, mine was running 4.0.0 prior to right now)

**Comment by maxogden** [comment]
i just upgraded to latest, hope that helps

**Comment by bcomnes** [comment]
Still at 0 peers, but I'm on a personaltelco connection right now.

**Comment by noffle** [comment]
I'm also stuck at zero peers on a fresh install.

**Comment by noffle** [comment]
Sanity check: are there people actually actively running friends or peerbot?

**Comment by ngoldman** [comment]
I have not run it in a long while. It's very possible no one is currently running it.

**Comment by bcomnes** [comment]
Last I heard we were waiting on a chrome webRTC memory leak (that caused hubs to crash eventually) to be fixed.  I don't have any detail links off hand atm.

**Comment by bnolan** [comment]
Any more details on this webrtc leak? I've been working on a similair app using a chrome extension that uses peer.js in a background page and it has run for a few days pretty reliably. Any pointers on what to look for?

**Comment by beaugunderson** [comment]
more details here:

https://github.com/js-platform/node-webrtc/issues/201

**Comment by maxogden** [comment]
I fixed the existing signalhub issues in Friends for now. App should be working now. `friend-swarm` needs some more perf testing with large swarms though
