### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by hackerkid** [moose-team/friends#137]
> friends@1.0.0 start /home/vishnu/code/friends
> npm run build-css && electron index.js 2>&1 | silence-chromium

> friends@1.0.0 build-css /home/vishnu/code/friends
> mkdirp dist && stylus -u nib css/app.styl -o dist/ -c

sh: 1: mkdirp: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by bcomnes** [comment]
Did you npm install and rebuild leveldb?

**Comment by hackerkid** [comment]
yes. I did both. I thought the error was due to the renaming of node to nodejs by debian so I installed the nodejs-legacy package in my ubunutu. It didn't change anything.

**Comment by ngoldman** [comment]
@hackerkid weird! `mkdirp` should be getting discovered by npm as a binary in `node_modules/.bin/` as long as `npm install` has been run. This may be an issue with how Debian and node are interacting... not sure how to debug from here. You can try installing mkdirp globally to see if it's a local discovery problem.

**Comment by hackerkid** [comment]
@ngoldman It solved the issue. mkdirp must not have been installed properly before.

**Comment by ngoldman** [comment]
@hackerkid you shouldn't need to install it globally -- if you run into the issue again let me know.
