### ISSUE TITLE
Update Node version number from io.js, even if it is Node v4 to avoid confusion.

### ISSUE THREAD

**Issue by bnb** [moose-team/friends#149]
Hey. I just took a look at the install instructions and they say io.js 1.8.1 is the minimum required version. It would be smart to either note that it works with Node v4+ or change the minimum version to Node v4.

**Comment by cpdean** [comment]
https://iojs.org/en/ even mentions that it has been merged back into nodejs

<img width="767" alt="io_js_-_javascript_i_o" src="https://cloud.githubusercontent.com/assets/160099/10952348/3f9457be-8310-11e5-9254-bfe8659ceb40.png">

**Comment by noffle** [comment]
Fixed in 4fff70c46d8c3d4e15505cf35b5e33e90f20419a
