### ISSUE TITLE
friends not working on Windows

### ISSUE THREAD

**Issue by somebody1234** [moose-team/friends#154]
When I try to rebuild-leveldown on windows, it have to replace `$(../../version.js)` with the actual version, and then it gets stuck when trying to build with msbuild.

**Comment by gggin** [comment]
same error!

**Comment by ngoldman** [comment]
Sorry, looks like #153 is causing some issues. May need to revert the last pull request -- I'll look into it.

**Comment by ngoldman** [comment]
This should be resolved now.

**Comment by gggin** [comment]
good
