### ISSUE TITLE
Use standard github user in gitconfig

### ISSUE THREAD

**Issue by ungoldman** [moose-team/friends#160]
This has been bugging me since the early days but I figured it was too tiny a nitpick to bring up, but since development is at a standstill, now's the perfect time!

A standard for storing github user information already existed before this project, all the way back in 2008.

```
git config --global github.user defunkt
```

> https://github.com/blog/180-local-github-config

I think we should use that instead of `git config --global git.username` to avoid unnecessary duplication of the same info in `.gitconfig` files the world over.

**Comment by beaugunderson** [comment]
makes total sense, should probably be filed against github-current-user though:

https://github.com/beaugunderson/github-current-user/blob/master/github-current-user.js#L14

**Comment by ungoldman** [comment]
:+1: will do

**Comment by ungoldman** [comment]
Thanks @beaugunderson! Bumped `github-current-user` so both forms are now supported. Some extra googling tells me both forms are out there in abundance, the former one a bit moreso.

- `"git config --global github.user"`: About 2,140 results
- `"git config --global user.username"`: About 2,690 results

¯\\\_(ツ)\_/¯
