### ISSUE TITLE
Friendly user beta

### ISSUE THREAD

**Issue by axel-rutz** [moose-team/friends#171]
Folks, this is really exciting, carry on! I want to open this ticket to get announced as soon as friendly non-developers can be bugged with using this. (or may this work now? how stable?)

**Comment by ungoldman** [comment]
Hi @axel-rutz, thank you for your enthusiasm! Unfortunately the core team that originally created `friends` has not been maintaining this project for quite some time. If you're interested in trying to get it working again to the point that it can be packaged and released, contributions are very welcome! I would love to see this project get released by someone enthusiastic about finishing what we started 😄

**Comment by axel-rutz** [comment]
thanks @ungoldman for that information - although it's not what i hoped to hear. so all i can say now is "if someone pushes this further, count me in for some testing and evangelism..".

**Comment by bcomnes** [comment]
@axel-rutz there is a light weight alternative https://substack.neocities.org/chatwizard/#lobby that has less features, but works reliably with webRTC enabled browsers.

**Comment by axel-rutz** [comment]
hey, thanks a lot for that, will definitely check it out!
