### ISSUE TITLE
web components

### ISSUE THREAD

**Issue by knownasilya** [moose-team/friends#20]
This would be a good platform for using web-components, since this is an installed app and speed isn't such an issue or number of bytes for the payload.

This would also allow reusing existing [customelements.io] content and maybe polymer paper elements (if using polymer). 

Apart from that, it would allow for a wider audience to understand the code-base and contribute more freely.

[customelements.io]: http://customelements.io

**Comment by shama** [comment]
FWIW, we chatted about this a bit and I personally think web components are cool.

But I think writing them now as generic JS prototypes will make it easy to wire up adapters to web components or React or even Ember, down the road. Without creating peer deps to frameworks.

IMO, the current architecture is fairly simple (data down, actions up):

```js
// Create an Element "class"
function Element (params) {
  if (!(this instanceof Element)) return new Element(params)

  // Default properties
  params = params || {}
  this.prop = params.prop || 'default'

  // Initialize other elements as nested deps and pass data down
  this.view = new OtherElement(params.otherParams)
}

// Create a lean render call that returns the DOM nodes
Element.prototype.render = function() {
  return h('.element', this.view.render())
}
```

That element can be `EnhancedElement.prototype = Object.create(Element.prototype)` like any other JS class to be extended. The `render` method itself or the nodes it returns can be adapted to other libraries.

---

We also have the option to pass in a root DOM node to the element and let it be completely self contained. Meaning it handles it's own DOM diffing and render.

Currently we just have a single render loop but we don't have to.

**Comment by knownasilya** [comment]
I guess that's not too made of an idea.

While you're doing that, might as well use Babel and write ES6 classes, since you are doing that anyway.

**Comment by shama** [comment]
High level APIs are convenient but if we run off and create a bunch of elements then that high level API changes (which new libs/frameworks tend to do often), it breaks all our elements every time they update.

My code breaking on every framework update is far more annoying to me than asking people to write plain javascript. :)

P.S. Babel "classes" are just syntax sugar that writes the same code as above. Except we don't need an extra build step, we can just write what Babel was going to transpile for us.

FWIW, I'm not against any of these suggestions but just letting you know these decisions were thought through and the reasoning behind them.

**Comment by knownasilya** [comment]
> FWIW, I'm not against any of these suggestions but just letting you know these decisions were thought through and the reasoning behind them.

I didn't feel like you were :smile_cat: and I'm just putting these thoughts out there.

> P.S. Babel "classes" are just syntax sugar that writes the same code as above. Except we don't need an extra build step, we can just write what Babel was going to transpile for us.

And the build step could be added to the existing one :+1:.

P.S. Is it possible to setup a livereload with an electron app (for dev)?

**Comment by feross** [comment]
> Is it possible to setup a livereload with an electron app (for dev)?

Yeah! You can just run `npm run watch` to automatically recompile the stylus. Then just hit CMD+R in the app to test.
