### ISSUE TITLE
Seperate hyperlog per room

### ISSUE THREAD

**Issue by calvinmetcalf** [moose-team/friends#21]
Basically joining a room would be the equivalent subscribing to a feed. 

Would allow for more complex irc style permissions, E. G. Being voiced would be a white list of users allowed to post with replicating clients rejecting posts not signed by them, owner would be the root node etc. 

No idea how feasible it is to do in hyper log

**Comment by mafintosh** [comment]
we we're just talking about that. this will also allow for private rooms etc and i think it's easily doable actually

**Comment by ngoldman** [comment]
yay sounds good
