### ISSUE TITLE
can't build on linux

### ISSUE THREAD

**Issue by calvinmetcalf** [moose-team/friends#23]
get a 403 when trying to download https://atom.io/download/atom-shell/v0.25.1/iojs-v0.25.1.tar.gz

**Comment by ngoldman** [comment]
@calvinmetcalf lmk if this is relevant to your probs at all: https://github.com/moose-team/friends/issues/5#issuecomment-96793479

**Comment by mafintosh** [comment]
@sorribas joined earlier using ubuntu so it works sometimes at least

**Comment by calvinmetcalf** [comment]
yeah I got on by using nvm to switch to node 0.12 which downloaded it from the correct url (https://atom.io/download/atom-shell/v0.25.1/node-v0.25.1.tar.gz) and then switching back to iojs
