### ISSUE TITLE
img and/or open graph parsing

### ISSUE THREAD

**Issue by derekr** [moose-team/friends#29]
Understandably not a desired feature, but I appreciate link/og parsing found in apps like slack and hipchat. Happy to work on it, but looking for some feedback on if this is wanted before I spend some time on it.

**Comment by maxogden** [comment]
+1 to gifs/pngs/jpgs for starters

would be nice to have a 'embed-media' module that matched strings for media urls, then turned them into embed html. bonus points if it can verify they are valid images before rendering (e.g. render to invisible canvas and make sure it loads correctly)

**Comment by maxogden** [comment]
since we have markdown now all you need to do is transform .jpg, .png, .gif into `![meta](url)`

**Comment by derekr** [comment]
Yeah I think that work for now. To provide a decent experience like slack (verifying a valid url and what not) message parsing would need be async and was more work than I could put in to it last night haha.

**Comment by derekr** [comment]
Thoughts from last night:

```
message = richMessage(message)

// parse <a> from rendered html
// check for first valid embed (or just grab the first url and if it doesn't work then ¯\_(ツ)_/¯
parseEmbeds(message, cb (err, embed) {
  // embed could share the same structure as a message { text: 'url', html: 'embed html' }
  message = richMessage.mergeMessages(message, embed)
  render()
})
```

- Loading/parsing indicator
- Ensuring embed renders below relevant message and not at the bottom of all merged messages

**Comment by beaugunderson** [comment]
some node tools for oembed parsing/lists of oembed URLs:

- https://github.com/punkave/oembetter
- https://github.com/inspiredjw/oembed-auto/blob/master/src/oembedList.json
- https://github.com/Doist/media-parser/blob/master/lib/media-parser.js
- https://github.com/Singly/hallway/blob/7a5fadc8e2d550dd374f85d8e17e0b4447e0b1aa/lib/services/links/oembed.js (the embed.ly API key in this file still works... haha)

**Comment by Flet** [comment]
This issue was moved to moose-team/rich-message#2
