### ISSUE TITLE
highlight mentions

### ISSUE THREAD

**Issue by ngoldman** [moose-team/friends#31]
e.g. you are `ngoldman`

replace any instances of `ngoldman` in message text with `<span class="highlight">ngoldman</span>`

trying to figure this out but [virtual-dom](https://github.com/Matt-Esch/virtual-dom) is making the solution not obvious to me

**Comment by ngoldman** [comment]
add `.highlight` class in fa1cd15433147f358215a68fa6f75ed9e612befe

**Comment by shama** [comment]
I believe [this lib](https://github.com/moose-team/friends/blob/master/lib/rich-message.js) will convert the text from the swarm into rich html and then converted to a vdom. In which the [messages element](https://github.com/moose-team/friends/blob/master/lib/elements/messages.js#L28) will read.

So we'd need to pass the `username` to the `richMessage` lib somehow to parse or move that rich message implementation under the messages element and pass the `self.data.username` to the messages element when rendering.

**Comment by feross** [comment]
@ngoldman I started working on this. It's nearly there in my local branch. I'll finish in the morning. Last thing to do is handle highlights correctly in "merged" consecutive messages.

**Comment by feross** [comment]
This is fixed now with https://github.com/moose-team/friends/commit/86aa9763a09b27d9228cb08535aa447b318bea27

**Comment by ngoldman** [comment]
:+1:
