### ISSUE TITLE
Is iojs supported?

### ISSUE THREAD

**Issue by DamonOehlman** [moose-team/friends#5]
First up - you had me at hello, this is awesome.

Second - I was getting a failure trying to run the `npm run rebuild` under iojs but after switching nvm back to `0.12` it was happy.  Is that something specific to my setup or is iojs support for atom (seemed to be the problem) still in the works?

```
> friends@0.0.0 rebuild /home/doehlman/code/github/friends/app
> cd node_modules/leveldown && HOME=~/.electron-gyp node-gyp rebuild --target=0.25.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell

gyp http GET https://atom.io/download/atom-shell/v0.25.1/iojs-v0.25.1.tar.gz
gyp http 403 https://atom.io/download/atom-shell/v0.25.1/iojs-v0.25.1.tar.gz
...
```

**Comment by maxogden** [comment]
you gotta have latest iojs and npm and then it should work

**Comment by DamonOehlman** [comment]
Reckon it must be an nvm thing then as I was on `1.8.1` - will investigate a bit more though...

**Comment by ngoldman** [comment]
@DamonOehlman I got a 403 for the same thing on a second machine I was testing on, its `~/.gitconfig` had the following:

```
[url "https://"]
  insteadOf = git://
```

once I removed that it was good to go. Hope that helps :dog:
