### ISSUE TITLE
bring back :cat2:

### ISSUE THREAD

**Issue by maxogden** [moose-team/friends#52]
![screen shot 2015-04-29 at 1 28 40 pm](https://cloud.githubusercontent.com/assets/39759/7400711/b33730ec-ee73-11e4-8c86-845fc86c0872.png)

when @flet switched to twemoji we got their crappy cat2 emoji

this is the true cat2 emoji:

![cat2](https://cloud.githubusercontent.com/assets/39759/7400715/c7777396-ee73-11e4-939e-c1d82c128053.png)

**Comment by beaugunderson** [comment]
this has my unequivocal support :cat2: :100:

**Comment by ngoldman** [comment]
how do we ensure proper :cat2: tribute as well as emoji equality across platforms? #48

**Comment by Flet** [comment]
@maxogden [I have offended your family, and I have offended a shaolin temple.](https://www.youtube.com/watch?v=W7-roiI5Vqc). Many apologies.

Something like [wemoji](https://www.npmjs.com/package/wemoji) may be a good alternative.

**Comment by jden** [comment]
:cat2: :cat2:

**Comment by jden** [comment]
@ngoldman perhaps some sort of feature-detection to see if emoji display properly, and then twemoji or similiar as a fallback?

**Comment by ngoldman** [comment]
can haz :cat2:? not sure how to feature detect for emoji support from w/in JS but I imagine it's possible

**Comment by jden** [comment]
rough idea: render raw unicode emoji off-screen, measure height and width of element

**Comment by Flet** [comment]
Relevant https://gist.github.com/mwunsch/4710561#file-emoji_image_replace-js-L71

**Comment by Flet** [comment]
This issue was moved to moose-team/rich-message#4
