### ISSUE TITLE
Does not handle thin windows well

### ISSUE THREAD

**Issue by Adjective-Object** [moose-team/friends#64]
Typing a message in the textarea draws focus to the right of the textarea, which expands beyond the right side of the screen on small windows.

I'd argue that chat programs are likely to be open alongside other windows, so a thin window is a use case worth considering.

![image](https://cloud.githubusercontent.com/assets/1174858/7401842/3c7f8a9a-ee95-11e4-903e-6caaa3060d91.png)

**Comment by maxogden** [comment]
i'm gonna consolidate all your textarea issues into one issue
