### ISSUE TITLE
Create new repo moose-team/enrich-message for rich-message.js

### ISSUE THREAD

**Issue by Flet** [moose-team/friends#65]
It feels like `/lib/rich-message.js` could be a nice little separate module that could be useful outside of `friends` too.

Any thoughts around separating it into another module at this time? Maybe `moose-team/enrich-message`? Or is this still premature?

**Comment by maxogden** [comment]
i think this is a good idea

**Comment by beaugunderson** [comment]
i like this too!

**Comment by ngoldman** [comment]
+1 rich-message module

**Comment by Flet** [comment]
OK, going to set up a new repo `rich-message`
