### ISSUE TITLE
feature: tab completion on user names mid-sentence

### ISSUE THREAD

**Issue by MylesBorins** [moose-team/friends#66]
I'm lazy... if I could have tab completion for my thoughts I would

**Comment by beaugunderson** [comment]
this works at the start of a line; do you also want it to work later in the line? (I'm +1 on that but want to clarify if that's what you're asking for)

**Comment by TheAlphaNerd** [comment]
hmmm... I didn't notice it working, but alas you are correct.

Although tab completion mid sentence would be nice

**Comment by beaugunderson** [comment]
cool I'll leave this open for the feature enhancement :)
