### ISSUE TITLE
bug: notifcation counter not resetting

### ISSUE THREAD

**Issue by MylesBorins** [moose-team/friends#67]
after I get a notification and click on the client the counter does not go down.

OSX

**Comment by TheAlphaNerd** [comment]
This is also causing weirdness in switching channels. If you switch to a channel it will forever go to where you were mentioned

**Comment by FotoVerite** [comment]
Bug is duplicated on mavricks.

**Comment by bnvk** [comment]
Can verify bug on Mavricks 10.9.5 but not having the channel switching issue @TheAlphaNerd mentions!
