### ISSUE TITLE
feature: too many cooks (messages)

### ISSUE THREAD

**Issue by MylesBorins** [moose-team/friends#68]
Currently you are blasted with all the messages from for ever when joining a channel.  It would be nice to be able to page and only see the latest sub set when joining. This could be a great feature to include in Friends golden platinum edition, or potential keep in a roadmap to pitch to investors.

**Comment by beaugunderson** [comment]
ha! I think there's an open issue to only show the last 500 or so on join (with the intent that the rest are searchable)

**Comment by TheAlphaNerd** [comment]
there�s no reason why all the messages can�t be stored, but only a subset are presented.

Search for old messages seems obtuse� 500 messages seems overwhelming.

**Comment by beaugunderson** [comment]
doesn't have to be 500 :) ideally it will work like irccloud/slack/hipchat; you join a channel, see some context (a not-terrible amount of previous messages), and are able to search the history that's replicated to you from peers

**Comment by ngoldman** [comment]
+1 @beaugunderson I think latest history with option to load more incrementally all the way back would work great. Ideally there would be an indicator of past mentions/messages you haven't read too (also like irccloud).

**Comment by FotoVerite** [comment]
I think a setting for how many are displayed makes the most sense at the moment

**Comment by maxogden** [comment]
I believe @mafintosh is working on a DB change so that messages will be sorted by date and we will have total message counts per-room. This will make it easier to change the UI to paginate arbitrarily forwards and backwards in time. Until then I would hesitate to do any major work on this

**Comment by ungoldman** [comment]
they were good ideas myles

**Comment by ungoldman** [comment]
to be fair to myles I think friends can be safely said to be abandonware, and i bet some folks don't like having zillions of open issues under https://github.com/issues

**Comment by MylesBorins** [comment]
I was just cleaning house... I left my other issues on here open to gauge response.. we can reopen if people like the issue
