### ISSUE TITLE
Create a Friends <--> IRC bridge

### ISSUE THREAD

**Issue by bnvk** [moose-team/friends#80]
If users could subscribe to IRC channels from within the Friends interface whereby the IRC conversations are replicated to the Friends DB, that would super cool.

Seems like setting up a server instance that uses peerbot and listens to IRC for events should be doable!

**Comment by ngoldman** [comment]
👍

**Comment by pokemonmegaman** [comment]
Something like `!peerbot IRC <irc channel>`?  Also, should this be one-way where we can only get messages from IRC, or should it be possible for peerbot to send messages to IRC as well?

**Comment by tunnckoCore** [comment]
:+1: yea would be absolutely cool.

**Comment by ngoldman** [comment]
peerbot has been broken out into https://github.com/moose-team/peerbot, that might serve as a starting point to an IRC bridge.

@pokemonmegaman ideally bridges are two way (see https://github.com/finnp/gitter-irc-bot for an example).

**Comment by ekmartin** [comment]
I'm working on a two way bridge based on [slack-irc](https://github.com/ekmartin/slack-irc) and peerbot, should have something functioning up soon.

**Comment by bcomnes** [comment]
Nice @ekmartin!

**Comment by ekmartin** [comment]
https://github.com/ekmartin/friends-irc - sends messages back and forth between the channels provided in the config.

Right now it posts messages to the Swarm channel as an anonymous user with the IRC message author's username, but it might be good to make it more explicit. 
@ngoldman suggested posting the messages from IRC -> Swarm as one user and rather put the username in the message body, similar to how the messages from Swarm -> IRC are posted now (`<username> message` by one IRC user). 
@bcomnes also suggested posting the messages to Swarm as `(IRC) username`.

I've set it up in #friends on Freenode, give it a try :)

![screen shot 2015-05-03 at 12 39 55 am](https://cloud.githubusercontent.com/assets/3536982/7443019/58d1c830-f12d-11e4-9c07-91c8c094da84.png)

**Comment by beaugunderson** [comment]
score! what's the repo for it (so we can close this and add new issues there if necessary?)

**Comment by beaugunderson** [comment]
oh oops i see it linked above!

**Comment by bnvk** [comment]
Awesome y'all :+1:

**Comment by ekmartin** [comment]
If you think it's a good idea and a decent implementation I wouldn't mind transferring the [repo](https://github.com/ekmartin/friends-irc) to moose-team.

**Comment by ngoldman** [comment]
@ekmartin please do so!
