### ISSUE TITLE
add basic chat commands -- /join

### ISSUE THREAD

**Issue by ngoldman** [moose-team/friends#94]
I think easiest and most obvious candidate to start a chat command pattern for now would be

`/join #channel`

metric of success: the channel is joined :sparkles:

**Comment by bcomnes** [comment]
Just jumping into the codebase here.  Any ideas where this should belong?

**Comment by beaugunderson** [comment]
one way would be to listen for a new event like `executeCommand` in app.js, like we listen for `sendMessage` now; and then in `lib/elements/composer.js` emit an `executeCommand` if the value begins with a `/` (in the `submit` function)

**Comment by beaugunderson** [comment]
and if the command is `/join` you can emit either an `addChannel` from `executeCommand` with the name of the channel and it should Just Work :sparkles:

**Comment by bcomnes** [comment]
:+1: Ok, I'll see what I can do

**Comment by pokemonmegaman** [comment]
Would a channel #foo want to be joined with "/join foo" or "/join #foo"?

**Comment by beaugunderson** [comment]
both of those should join `#foo`

**Comment by ngoldman** [comment]
@beaugunderson++ I think mimicking IRC conventions is the way to go for now

**Comment by bcomnes** [comment]
Im +1 on mimicking IRC where we can

**Comment by tunnckoCore** [comment]
And Im +1 but then we need `/alias` command :dog2:

**Comment by Flet** [comment]
This is cool!

It might make sense to eventually push the command processing into its own js file... I suspect there will be a flood of commands coming :)

**Comment by tunnckoCore** [comment]
> It might make sense to eventually push the command processing into its own js file... 

maybe when something like "custom aliases api" is implemented.

**Comment by tunnckoCore** [comment]
^ hm.. okey, maybe not, but its good idea to externalize this stuff https://github.com/moose-team/friends/blob/master/app.js#L190-L298
